#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT="${OUTPUT:-${ROOT_DIR}/.generated/values.runtime-detected.yaml}"
MODE="${MODE:-auto}"
GPU_RESOURCE="${GPU_RESOURCE:-nvidia.com/gpu}"

usage() {
  cat <<'EOF'
Usage: hack/detect-runtime-profile.sh [--mode auto|nvidia|cpu] [--output FILE]

Detects Kubernetes runtime capacity and writes a Helm values overlay:
  - nvidia: use runtimeClassName=nvidia and request nvidia.com/gpu
  - cpu: clear NVIDIA runtime/GPU scheduling and run Ollama on CPU

The generated file is intentionally ignored by git.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode)
      MODE="${2:-}"
      shift 2
      ;;
    --output)
      OUTPUT="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "${MODE}" in
  auto|nvidia|cpu) ;;
  *)
    echo "--mode must be auto, nvidia, or cpu" >&2
    exit 2
    ;;
esac

command -v kubectl >/dev/null || { echo "missing required command: kubectl" >&2; exit 1; }
kubectl cluster-info >/dev/null

gpu_nodes="$(
  kubectl get nodes \
    -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.allocatable.nvidia\.com/gpu}{"\n"}{end}' |
    awk 'NF >= 2 && $2 ~ /^[0-9]+$/ && $2 > 0 { print $1 ":" $2 }'
)"
cpu_nodes="$(
  kubectl get nodes \
    -o jsonpath='{range .items[*]}{.metadata.name}{" "}{.status.allocatable.cpu}{"\n"}{end}' |
    awk 'NF >= 2 && $2 != "" { print $1 ":" $2 }'
)"

if [[ "${MODE}" == "auto" ]]; then
  if [[ -n "${gpu_nodes}" ]]; then
    MODE="nvidia"
  elif [[ -n "${cpu_nodes}" ]]; then
    MODE="cpu"
  else
    echo "no allocatable Kubernetes CPU capacity detected" >&2
    exit 1
  fi
fi

if [[ "${MODE}" == "nvidia" && -z "${gpu_nodes}" ]]; then
  echo "requested NVIDIA mode, but Kubernetes does not advertise ${GPU_RESOURCE}" >&2
  exit 1
fi
if [[ "${MODE}" == "cpu" && -z "${cpu_nodes}" ]]; then
  echo "requested CPU mode, but Kubernetes CPU capacity could not be detected" >&2
  exit 1
fi

mkdir -p "$(dirname "${OUTPUT}")"

if [[ "${MODE}" == "nvidia" ]]; then
  cat >"${OUTPUT}" <<EOF
# Generated by hack/detect-runtime-profile.sh. Do not commit.
runtime:
  accelerator: nvidia
  detectedGpuNodes: "${gpu_nodes//$'\n'/,}"
nvidia:
  runtimeClassName: nvidia
  gpuResourceName: ${GPU_RESOURCE}
  gpuCount: 1
ollama:
  runtimeClassName: nvidia
  nodeSelector: null
  ollama:
    gpu:
      enabled: true
      type: nvidia
      number: 1
      nvidiaResource: ${GPU_RESOURCE}
dcgm-exporter:
  enabled: true
monitoring:
  dcgmExporter:
    serviceMonitor:
      enabled: false
EOF
else
  cat >"${OUTPUT}" <<EOF
# Generated by hack/detect-runtime-profile.sh. Do not commit.
runtime:
  accelerator: cpu
  detectedCpuNodes: "${cpu_nodes//$'\n'/,}"
nvidia:
  runtimeClassName: ""
  gpuResourceName: ${GPU_RESOURCE}
  gpuCount: 0
gpu-operator:
  enabled: false
nvidia-device-plugin:
  enabled: false
dcgm-exporter:
  enabled: false
monitoring:
  dcgmExporter:
    serviceMonitor:
      enabled: false
ollama:
  runtimeClassName: ""
  nodeSelector: null
  ollama:
    gpu:
      enabled: false
      type: nvidia
      number: 0
      nvidiaResource: ${GPU_RESOURCE}
EOF
fi

echo "Detected ${MODE} runtime profile"
if [[ "${MODE}" == "nvidia" ]]; then
  echo "GPU nodes: ${gpu_nodes//$'\n'/, }"
else
  echo "CPU nodes: ${cpu_nodes//$'\n'/, }"
fi
echo "Wrote ${OUTPUT}"
